### ISSUE TITLE
Upload to telegram action

### ISSUE THREAD

**Issue by niqzart** [niqzart/backuper#7]

**Comment by niqzart** [comment]
https://github.com/devdetour/TelegramFUSE

**Comment by niqzart** [comment]
Possible data structure (on top built of compress action)
```
duplicate-third-party:
  type: telegram-upload  # use `7za a`
  source: "$BACKUP_BASE"
  password: "$ZIP_PASSWORD"  # may be `None`
  volume_size: 2g  # `7za a ... -v{size}[b | k | m | g]`
  temp_folder: "%Temp%/backuper"  # mb use relative path
```
